name: Propose Stable Release
on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: Release Type
        options:
          - build
          - minor
          - major
jobs:
  update_version:
    uses: neongeckocom/.github/.github/workflows/propose_semver_release.yml@FEAT_OvosPackageSupport
    with:
      release_type: ${{ inputs.release_type }}
      version_file: ovos_utils/version.py
      alpha_var: VERSION_ALPHA
      build_var: VERSION_BUILD
      minor_var: VERSION_MINOR
      major_var: VERSION_MAJOR
  generate_release_notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Build Tools
        run: |
          python -m pip install build wheel
      - name: Remove alpha (declare stable)
        run: |
          VER=$(python setup.py --version)
          python scripts/remove_alpha.py
      - name: "Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        id: changelog
      - name: Commit to dev
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Declare alpha stable
          branch: dev
  pull_changes:
    uses: neongeckocom/.github/.github/workflows/pull_master.yml@master
    with:
      pr_assignee: ${{ github.actor }}
